name: Deploy Amplify App with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./cloud/src

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./cloud/src
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: deploy
        run: |
          URL="${{ secrets.WEBHOOK_URL }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
